### ISSUE TITLE
Pact verification should fail fast if invalid ProviderStates*URL provided

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-go#8]
If the endpoint referenced by `/setup` or `/states` is invalid, as expected by the verifier, Pact should fail fast with a clear warning:

```
    if err := pact.VerifyProvider(types.VerifyRequest{
        ProviderBaseURL:        fmt.Sprintf("http://localhost:%d", port),
        PactURLs:               pactFiles,
        ProviderStatesURL:      fmt.Sprintf("http://localhost:%d/states", port),
        ProviderStatesSetupURL: fmt.Sprintf("http://localhost:%d/setup", port),
    }); err != nil {
        t.Errorf("verification failed: %v", err)
    }
```

At the moment, an obscure error message from the verifier is recorded:

```/Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/app/lib/pact/provider_verifier/pact_helper.rb:33:in`<top (required)>': undefined method `keys' for nil:NilClass (NoMethodError)
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/pact-1.9.1/lib/pact/cli/run_pact_verification.rb:43:in`load'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/pact-1.9.1/lib/pact/cli/run_pact_verification.rb:43:in `load_pact_helper'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/pact-1.9.1/lib/pact/cli/run_pact_verification.rb:21:in`call'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/pact-1.9.1/lib/pact/cli/run_pact_verification.rb:14:in `call'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/app/lib/pact/provider_verifier/app.rb:65:in`block in verify_pacts'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/app/lib/pact/provider_verifier/app.rb:54:in `collect'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/app/lib/pact/provider_verifier/app.rb:54:in`verify_pacts'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/app/lib/pact/provider_verifier/cli.rb:18:in `verify'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
            from /Users/mfellows/Downloads/darwin-amd64/pact-provider-verifier/lib/app/pact-provider-verifier.rb:3:in`<main>'

```
```

**Comment by mefellows** [comment]
Closing - this field is now deprecated!
